//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ApiRestPrueba.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class TmCapEntities : DbContext
    {
        public TmCapEntities()
            : base("name=TmCapEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<categoria> categoria { get; set; }
        public virtual DbSet<compra> compra { get; set; }
        public virtual DbSet<detalle_compra> detalle_compra { get; set; }
        public virtual DbSet<producto> producto { get; set; }
        public virtual DbSet<rol> rol { get; set; }
        public virtual DbSet<solicitud> solicitud { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    
        public virtual int sp_insert_compra(Nullable<System.DateTime> fecha_compra, Nullable<int> id_usuario, string tipo_comprobante, string serie_comprobante, string num_comprobante, Nullable<decimal> impuesto, Nullable<int> total, string estado)
        {
            var fecha_compraParameter = fecha_compra.HasValue ?
                new ObjectParameter("fecha_compra", fecha_compra) :
                new ObjectParameter("fecha_compra", typeof(System.DateTime));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var tipo_comprobanteParameter = tipo_comprobante != null ?
                new ObjectParameter("tipo_comprobante", tipo_comprobante) :
                new ObjectParameter("tipo_comprobante", typeof(string));
    
            var serie_comprobanteParameter = serie_comprobante != null ?
                new ObjectParameter("serie_comprobante", serie_comprobante) :
                new ObjectParameter("serie_comprobante", typeof(string));
    
            var num_comprobanteParameter = num_comprobante != null ?
                new ObjectParameter("num_comprobante", num_comprobante) :
                new ObjectParameter("num_comprobante", typeof(string));
    
            var impuestoParameter = impuesto.HasValue ?
                new ObjectParameter("impuesto", impuesto) :
                new ObjectParameter("impuesto", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_compra", fecha_compraParameter, id_usuarioParameter, tipo_comprobanteParameter, serie_comprobanteParameter, num_comprobanteParameter, impuestoParameter, totalParameter, estadoParameter);
        }
    
        public virtual int sp_insert_detaCompra(Nullable<int> p_CANTIDAD, Nullable<int> p_PRECIO, Nullable<int> p_ID_COMPRA, Nullable<int> p_ID_PRODUCTO, Nullable<int> p_DESCUENTO)
        {
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(int));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(int));
    
            var p_ID_COMPRAParameter = p_ID_COMPRA.HasValue ?
                new ObjectParameter("P_ID_COMPRA", p_ID_COMPRA) :
                new ObjectParameter("P_ID_COMPRA", typeof(int));
    
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(int));
    
            var p_DESCUENTOParameter = p_DESCUENTO.HasValue ?
                new ObjectParameter("P_DESCUENTO", p_DESCUENTO) :
                new ObjectParameter("P_DESCUENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_detaCompra", p_CANTIDADParameter, p_PRECIOParameter, p_ID_COMPRAParameter, p_ID_PRODUCTOParameter, p_DESCUENTOParameter);
        }
    
        public virtual int sp_insert_producto(string p_NOMBRE, string p_DESCRIPCION, Nullable<int> p_PRECIO, Nullable<int> p_ID_CATEGORIA, string p_CODIGO, Nullable<int> p_STOCK, Nullable<bool> p_ESTADO, byte[] p_IMAGEN)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(int));
    
            var p_ID_CATEGORIAParameter = p_ID_CATEGORIA.HasValue ?
                new ObjectParameter("P_ID_CATEGORIA", p_ID_CATEGORIA) :
                new ObjectParameter("P_ID_CATEGORIA", typeof(int));
    
            var p_CODIGOParameter = p_CODIGO != null ?
                new ObjectParameter("P_CODIGO", p_CODIGO) :
                new ObjectParameter("P_CODIGO", typeof(string));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(int));
    
            var p_ESTADOParameter = p_ESTADO.HasValue ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(bool));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_producto", p_NOMBREParameter, p_DESCRIPCIONParameter, p_PRECIOParameter, p_ID_CATEGORIAParameter, p_CODIGOParameter, p_STOCKParameter, p_ESTADOParameter, p_IMAGENParameter);
        }
    
        public virtual int sp_insert_solicitud(string p_MENSAJE, Nullable<int> p_TELEFONO, string p_MAIL, Nullable<System.DateTime> p_FECHA)
        {
            var p_MENSAJEParameter = p_MENSAJE != null ?
                new ObjectParameter("P_MENSAJE", p_MENSAJE) :
                new ObjectParameter("P_MENSAJE", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(int));
    
            var p_MAILParameter = p_MAIL != null ?
                new ObjectParameter("P_MAIL", p_MAIL) :
                new ObjectParameter("P_MAIL", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_solicitud", p_MENSAJEParameter, p_TELEFONOParameter, p_MAILParameter, p_FECHAParameter);
        }
    
        public virtual int sp_insert_usuario(string p_NOMBRE, string p_APELLIDOS, Nullable<System.DateTime> p_FECHA_NAC, string p_EMAIL, string p_CLAVE, string p_RUT, Nullable<int> p_ID_ROL, string p_DIRECCION, Nullable<int> p_TELEFONO, string p_ESTADO)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("p_NOMBRE", p_NOMBRE) :
                new ObjectParameter("p_NOMBRE", typeof(string));
    
            var p_APELLIDOSParameter = p_APELLIDOS != null ?
                new ObjectParameter("p_APELLIDOS", p_APELLIDOS) :
                new ObjectParameter("p_APELLIDOS", typeof(string));
    
            var p_FECHA_NACParameter = p_FECHA_NAC.HasValue ?
                new ObjectParameter("p_FECHA_NAC", p_FECHA_NAC) :
                new ObjectParameter("p_FECHA_NAC", typeof(System.DateTime));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("p_EMAIL", p_EMAIL) :
                new ObjectParameter("p_EMAIL", typeof(string));
    
            var p_CLAVEParameter = p_CLAVE != null ?
                new ObjectParameter("p_CLAVE", p_CLAVE) :
                new ObjectParameter("p_CLAVE", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("p_RUT", p_RUT) :
                new ObjectParameter("p_RUT", typeof(string));
    
            var p_ID_ROLParameter = p_ID_ROL.HasValue ?
                new ObjectParameter("p_ID_ROL", p_ID_ROL) :
                new ObjectParameter("p_ID_ROL", typeof(int));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("p_DIRECCION", p_DIRECCION) :
                new ObjectParameter("p_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("p_TELEFONO", p_TELEFONO) :
                new ObjectParameter("p_TELEFONO", typeof(int));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("p_ESTADO", p_ESTADO) :
                new ObjectParameter("p_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_insert_usuario", p_NOMBREParameter, p_APELLIDOSParameter, p_FECHA_NACParameter, p_EMAILParameter, p_CLAVEParameter, p_RUTParameter, p_ID_ROLParameter, p_DIRECCIONParameter, p_TELEFONOParameter, p_ESTADOParameter);
        }
    
        public virtual ObjectResult<sp_select_categoria_Result> sp_select_categoria()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_categoria_Result>("sp_select_categoria");
        }
    
        public virtual ObjectResult<sp_select_compra_Result> sp_select_compra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_compra_Result>("sp_select_compra");
        }
    
        public virtual ObjectResult<sp_select_detaCompra_Result> sp_select_detaCompra()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_detaCompra_Result>("sp_select_detaCompra");
        }
    
        public virtual ObjectResult<sp_select_producto_Result> sp_select_producto()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_producto_Result>("sp_select_producto");
        }
    
        public virtual ObjectResult<sp_select_rol_Result> sp_select_rol()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_rol_Result>("sp_select_rol");
        }
    
        public virtual ObjectResult<sp_select_solicitud_Result> sp_select_solicitud()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_solicitud_Result>("sp_select_solicitud");
        }
    
        public virtual ObjectResult<sp_select_usuario_Result> sp_select_usuario()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_select_usuario_Result>("sp_select_usuario");
        }
    
        public virtual int sp_update_compra(Nullable<int> id_compra, Nullable<System.DateTime> fecha_compra, Nullable<int> id_usuario, string tipo_comprobante, string serie_comprobante, string num_comprobante, Nullable<decimal> impuesto, Nullable<int> total, string estado)
        {
            var id_compraParameter = id_compra.HasValue ?
                new ObjectParameter("id_compra", id_compra) :
                new ObjectParameter("id_compra", typeof(int));
    
            var fecha_compraParameter = fecha_compra.HasValue ?
                new ObjectParameter("fecha_compra", fecha_compra) :
                new ObjectParameter("fecha_compra", typeof(System.DateTime));
    
            var id_usuarioParameter = id_usuario.HasValue ?
                new ObjectParameter("id_usuario", id_usuario) :
                new ObjectParameter("id_usuario", typeof(int));
    
            var tipo_comprobanteParameter = tipo_comprobante != null ?
                new ObjectParameter("tipo_comprobante", tipo_comprobante) :
                new ObjectParameter("tipo_comprobante", typeof(string));
    
            var serie_comprobanteParameter = serie_comprobante != null ?
                new ObjectParameter("serie_comprobante", serie_comprobante) :
                new ObjectParameter("serie_comprobante", typeof(string));
    
            var num_comprobanteParameter = num_comprobante != null ?
                new ObjectParameter("num_comprobante", num_comprobante) :
                new ObjectParameter("num_comprobante", typeof(string));
    
            var impuestoParameter = impuesto.HasValue ?
                new ObjectParameter("impuesto", impuesto) :
                new ObjectParameter("impuesto", typeof(decimal));
    
            var totalParameter = total.HasValue ?
                new ObjectParameter("total", total) :
                new ObjectParameter("total", typeof(int));
    
            var estadoParameter = estado != null ?
                new ObjectParameter("estado", estado) :
                new ObjectParameter("estado", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_compra", id_compraParameter, fecha_compraParameter, id_usuarioParameter, tipo_comprobanteParameter, serie_comprobanteParameter, num_comprobanteParameter, impuestoParameter, totalParameter, estadoParameter);
        }
    
        public virtual int sp_update_detaCompra(Nullable<int> p_ID_DETALLE, Nullable<int> p_CANTIDAD, Nullable<int> p_PRECIO, Nullable<int> p_ID_COMPRA, Nullable<int> p_ID_PRODUCTO, Nullable<int> p_DESCUENTO)
        {
            var p_ID_DETALLEParameter = p_ID_DETALLE.HasValue ?
                new ObjectParameter("P_ID_DETALLE", p_ID_DETALLE) :
                new ObjectParameter("P_ID_DETALLE", typeof(int));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(int));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(int));
    
            var p_ID_COMPRAParameter = p_ID_COMPRA.HasValue ?
                new ObjectParameter("P_ID_COMPRA", p_ID_COMPRA) :
                new ObjectParameter("P_ID_COMPRA", typeof(int));
    
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(int));
    
            var p_DESCUENTOParameter = p_DESCUENTO.HasValue ?
                new ObjectParameter("P_DESCUENTO", p_DESCUENTO) :
                new ObjectParameter("P_DESCUENTO", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_detaCompra", p_ID_DETALLEParameter, p_CANTIDADParameter, p_PRECIOParameter, p_ID_COMPRAParameter, p_ID_PRODUCTOParameter, p_DESCUENTOParameter);
        }
    
        public virtual int sp_update_producto(Nullable<int> p_ID_PROD, string p_NOMBRE, string p_DESCRIPCION, Nullable<int> p_PRECIO, Nullable<int> p_ID_CATEGORIA, string p_CODIGO, Nullable<int> p_STOCK, Nullable<bool> p_ESTADO, byte[] p_IMAGEN)
        {
            var p_ID_PRODParameter = p_ID_PROD.HasValue ?
                new ObjectParameter("P_ID_PROD", p_ID_PROD) :
                new ObjectParameter("P_ID_PROD", typeof(int));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(int));
    
            var p_ID_CATEGORIAParameter = p_ID_CATEGORIA.HasValue ?
                new ObjectParameter("P_ID_CATEGORIA", p_ID_CATEGORIA) :
                new ObjectParameter("P_ID_CATEGORIA", typeof(int));
    
            var p_CODIGOParameter = p_CODIGO != null ?
                new ObjectParameter("P_CODIGO", p_CODIGO) :
                new ObjectParameter("P_CODIGO", typeof(string));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(int));
    
            var p_ESTADOParameter = p_ESTADO.HasValue ?
                new ObjectParameter("P_ESTADO", p_ESTADO) :
                new ObjectParameter("P_ESTADO", typeof(bool));
    
            var p_IMAGENParameter = p_IMAGEN != null ?
                new ObjectParameter("P_IMAGEN", p_IMAGEN) :
                new ObjectParameter("P_IMAGEN", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_producto", p_ID_PRODParameter, p_NOMBREParameter, p_DESCRIPCIONParameter, p_PRECIOParameter, p_ID_CATEGORIAParameter, p_CODIGOParameter, p_STOCKParameter, p_ESTADOParameter, p_IMAGENParameter);
        }
    
        public virtual int sp_update_usuario(Nullable<int> p_ID_USUARIO, string p_NOMBRE, string p_APELLIDOS, Nullable<System.DateTime> p_FECHA_NAC, string p_EMAIL, string p_CLAVE, string p_RUT, Nullable<int> p_ID_ROL, string p_DIRECCION, Nullable<int> p_TELEFONO, string p_ESTADO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("p_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("p_ID_USUARIO", typeof(int));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("p_NOMBRE", p_NOMBRE) :
                new ObjectParameter("p_NOMBRE", typeof(string));
    
            var p_APELLIDOSParameter = p_APELLIDOS != null ?
                new ObjectParameter("p_APELLIDOS", p_APELLIDOS) :
                new ObjectParameter("p_APELLIDOS", typeof(string));
    
            var p_FECHA_NACParameter = p_FECHA_NAC.HasValue ?
                new ObjectParameter("p_FECHA_NAC", p_FECHA_NAC) :
                new ObjectParameter("p_FECHA_NAC", typeof(System.DateTime));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("p_EMAIL", p_EMAIL) :
                new ObjectParameter("p_EMAIL", typeof(string));
    
            var p_CLAVEParameter = p_CLAVE != null ?
                new ObjectParameter("p_CLAVE", p_CLAVE) :
                new ObjectParameter("p_CLAVE", typeof(string));
    
            var p_RUTParameter = p_RUT != null ?
                new ObjectParameter("p_RUT", p_RUT) :
                new ObjectParameter("p_RUT", typeof(string));
    
            var p_ID_ROLParameter = p_ID_ROL.HasValue ?
                new ObjectParameter("p_ID_ROL", p_ID_ROL) :
                new ObjectParameter("p_ID_ROL", typeof(int));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("p_DIRECCION", p_DIRECCION) :
                new ObjectParameter("p_DIRECCION", typeof(string));
    
            var p_TELEFONOParameter = p_TELEFONO.HasValue ?
                new ObjectParameter("p_TELEFONO", p_TELEFONO) :
                new ObjectParameter("p_TELEFONO", typeof(int));
    
            var p_ESTADOParameter = p_ESTADO != null ?
                new ObjectParameter("p_ESTADO", p_ESTADO) :
                new ObjectParameter("p_ESTADO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_update_usuario", p_ID_USUARIOParameter, p_NOMBREParameter, p_APELLIDOSParameter, p_FECHA_NACParameter, p_EMAILParameter, p_CLAVEParameter, p_RUTParameter, p_ID_ROLParameter, p_DIRECCIONParameter, p_TELEFONOParameter, p_ESTADOParameter);
        }
    }
}
